kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-udisk-rssd
  resources:
    requests:
      storage: 20Gi

