kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: udisk-ssd
  resources:
    requests:
      storage: 20Gi