apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-exmaple
 namespace: default
spec:
 scaleTargetRef:
   apiVersion: apps/v1beta1
   kind: Deployment
   name: hpa-example
 minReplicas: 1
 maxReplicas: 20
 targetCPUUtilizationPercentage: 50
